config/routes.rb
Rails.application.routes.draw do


  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root to: 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Attachinary::Engine => "/attachinary"

  get'pages/concept'

  resources :articles, only: [:index, :create, :new, :destroy, :update]

  get 'orders/myorders', to: 'orders#myorders', as: 'myorders'
  post 'orders/:id', to: 'orders#create', as: 'new_order'
  delete 'orders/:id', to: 'orders#destroy', as: 'destroy_order'

  get '/test', to: "orders#test"

  get 'orders/mysales', to: 'orders#mysales', as: 'mysales'

  get '/articles/search', to: 'articles#search'

  get 'orders/:id/:status', to: 'orders#change_statut', as: 'change_statut'

end

app/models/article.rb
class Article < ApplicationRecord

  has_attachment :photo
  belongs_to :user
  has_many :orders, dependent: :destroy
  validates :name, :quantity, :price, :unit, presence: true
  before_save :normalize

  enum active: [:inactif, :actif]

  def self.units
    ["kg", "g", "unités", "l"]
  end

  def normalize
    self.name.downcase!
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :search]
  after_action :flash_nil, only: :index

  def flash_nil
    flash[:notice] = nil
  end

  def index

    flash[:notice] = "Veuillez vous connecter pour commander" if current_user.nil?

    @articles = Article.actif.order(id: :desc)

    if params[:format].nil?
      @article = Article.new
    else
      @article = Article.find(params[:format])
    end
  end

  def create
    @article = Article.new(article_params)
    @article.active = :actif
    @article.user = current_user
    if @article.save
      redirect_to articles_path, notice: "L'article a été créé avec beaucoup de succès"
    else
      render :index
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to articles_path, notice: "L'article a été mis à jour"
    else
      render :index
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to mysales_path, notice: "L'article a été effacé ainsi que toutes les commandes qui lui sont liées"
  end

  def search
    params[:query].downcase!
    if params[:query] == ""
      redirect_to articles_path
    else
      @articles = Article.where('name LIKE :search', search: "%#{params[:query]}%")
      if @articles == nil
        @articles = Article.where('description LIKE :search', search: "%#{params[:query]}%")
      end
      flash[:notice] = "Veuillez vous connecter pour commander" if current_user.nil?
      render :index
    end
    # search = params[:query]
    # @results = ActiveRecord::Base.connection.execute("SELECT * FROM articles WHERE name = '#{search}'")
    # @articles = @results.to_a
    # redirect_to articles_search_path
  end


  private

  def set_article
    @article = Article.find(params[:id])

  end

  def article_params
    params.require(:article).permit(:name, :description, :quantity, :unit, :image, :price, :delivery_date, :photo)

  end



end

app/views/articles/_display_cards.html.erb
<div class="row">
    <% articles.each do |article| %>
    <div class="col-xs-12 col-sm-4 col-lg-3 flex">
      <div class="card-wrapper">
        <% if article.photo? %>
          <% photo = article.photo.path %>
        <% elsif article.image? %>
          <% photo = article.image %>
        <% else %>
          <% photo = "ak9nsluerudayro8of3c" %>
        <% end %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path photo, width: 270, height: 150, crop: :fill %>');">

          <div class="card-name-desc">
            <h2><%= article.name %></h2>
            <p><%= article.description %></p>
          </div>
          <div class="card-cart">
            <% if !current_user.nil? %>
            <%= link_to new_order_path(article), method: :post do %>
            <i class="fa fa-shopping-basket" aria-hidden="true"></i>
            <% end %>
            <% end %>
          </div>
        </div>
        <div class="card-details">
          <% if article.user.profile_picture? %>
            <%= cl_image_tag article.user.profile_picture.path, width:300, height:300, crop: :fill, gravity: :face, class: "card-user" %>
          <% elsif article.user.facebook_picture_url? %>
            <%= image_tag article.user.facebook_picture_url, class: "card-user" %>
          <% else %>
            <%= image_tag "http://placehold.it/30x30", class: "card-user" %>
          <% end %>
          <div class="card-vendor-name">
            <p><%= article.user.last_name %></p>
            <p><%= article.user.first_name %></p>
          </div>
          <div class="card-quantity-price">
            <%= article.quantity %><%= article.unit %> pour <%= article.price %>€
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>

app/views/articles/_form.html.erb
<%= simple_form_for @article do |f| %>
<%= f.error_notification %>
<%= f.input :name, placeholder: "nom", label: false %>
<%= f.input :description, placeholder: "description", label: false%>
<div class="form-group">
  <div class="col-xs-4">
    <%= f.input :quantity, placeholder: "quantity", label:false  %>
  </div>
  <div class="col-xs-4">
    <%= f.input :unit, placeholder: "unit", collection: Article.units, label:false %>
  </div>
  <div class="col-xs-4">
    <%= f.input :price, placeholder: "prix", label:false %>
  </div>
</div>
<%= f.input :photo, as: :attachinary, placeholder: "chemin image", label:false %>

<%= f.input :delivery_date, label: "DLC" %>
<%= f.submit "Valider", class: "btn" %>
<% end %>

app/views/articles/index.html.erb
<div class="container">

  <div class="row">
    <div class="searchbar">
      <form class="search" action="/articles/search" method= "get" >
        <input class="searchTerm"  type="text" placeholder="Rechercher" name="query" />
        </input>
        <input class="searchButton" type="submit">
      </form>
    </div>
  </div>


<%= render 'display_cards', articles: @articles %>


</div>

app/views/articles/search.html.erb
<div class="container">
<h1 class="text-center">L'Épicerie</h1>
<br>


<div class="container">

  <div class="col-md-8 col-lg-8 col-xs-12">
    <ul>
      <% @articles.each do |article| %>
      <li>

        <b> #<%= article.active %># <%= article.name %></b> : <%= article.description %>
        <br>
        <%= article.quantity %>
        <%= article.unit %>
        <br>
        prix : <i><b><%= article.price %>€</b></i>
        <br>
        <br>
        <%= link_to "delete", article_path(article), method: :delete, class: "btn btn-primary" %>
        <%= link_to "mettre à jour", articles_path(article), class: "btn btn-primary" %>
        <%= link_to "add to order", new_order_path(article), method: :post, class: "btn btn-primary" %>

        <br>
        -------------------
      </li>
      <% end %>
    </ul>
  </div>