config/routes.rb
Rails.application.routes.draw do


  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root to: 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Attachinary::Engine => "/attachinary"

  get'pages/concept'

  resources :articles, only: [:index, :create, :new, :destroy, :update]

  get 'orders/myorders', to: 'orders#myorders', as: 'myorders'
  post 'orders/:id', to: 'orders#create', as: 'new_order'
  delete 'orders/:id', to: 'orders#destroy', as: 'destroy_order'

  get '/test', to: "orders#test"

  get 'orders/mysales', to: 'orders#mysales', as: 'mysales'

  get '/articles/search', to: 'articles#search'

  get 'orders/:id/:status', to: 'orders#change_statut', as: 'change_statut'

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :user
  belongs_to :article

  enum status: [:en_cours,  :a_preparer, :confirme, :livre,  :annulle]
  # 1. acheteur cree order => en_cours
  # 2. acheteur confirme order => :a_preparer
  # 3. vendeur confirme preparation => :confirme
  # 4. acheteur confirme pickup => :livre
  # 5. vendeur, acheteur ont la possibilité d'annuler l'order

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :set_order, only: [:destroy, :change_statut]

  def myorders
    @order = Order.new
    @order.status = params[:status]
    if params[:status].nil?
      @order.en_cours!
    end

    if @order.en_cours?
      @orders = current_user.orders.en_cours
      render 'a'
    elsif @order.a_preparer?
      @orders = current_user.orders.a_preparer
      render '_b'
    elsif @order.confirme?
      @orders = current_user.orders.confirme
      render '_c'
    elsif @order.livre?
      @orders = current_user.orders.livre
      render '_d'
    end
  end

  def create
    @article = Article.find(params[:id])
    @order = Order.new(article_id: @article.id,
      user_id: current_user.id,
      status: :en_cours,
      comment: "new order"
      )
    if @order.save

      redirect_to myorders_path, notice: "Une commande a été créée"
    else
      render 'articles/index'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to myorders_path, notice: "La commande a été effacée"
  end


def mysales
# param du form
  if params[:format].nil?
    @article = Article.new
  else
    @article = Article.find(params[:format])
  end
  # articles en cours de vente pour le user
    @articles = Article.where(user_id: current_user)
    @array_articles = []
    # contruire array qui contient tous les articles du user
      @articles.each do |article|
        @array_articles << article.id
      end
    @orders = Order.all
    @orders_a_preparer = []
    @orders_livre =[]
    @orders_termine = []
    # garder les orders dont les articles <=> articles du user
    @orders.each do |order|
    @array_articles.each do |a|
      if order.article_id == a
        if order.a_preparer?
          @orders_a_preparer << order
        elsif order.confirme?
          @orders_livre << order
        elsif order.livre?
          @orders_termine << order
        end
      end
    end
  end
  @status = params[:status]
  @order = Order.new
  @order.status = params[:status]
     if params[:status].nil?
      @order.en_cours!
    end
  if @order.en_cours?
    render '_mesproduits'
  elsif @order.a_preparer?
    @orders = @orders_a_preparer
    render '_e'
  elsif @order.confirme?
    @orders = @orders_livre
    render '_f'
  elsif @order.livre?
    @orders = @orders_termine
    render '_g'
  end
end

def change_statut
  @order.status = params[:status]
  @order.save!
  if @order.a_preparer?
    redirect_to  myorders_path, notice: "La commande est confirmée! Le vendeur la prépare..."
  elsif @order.confirme?
    redirect_to  myorders_path, notice: "La commande est préparée"
  elsif @order.livre?
    redirect_to  myorders_path, notice: "La commande a été récupérée"
  elsif @order.annulle?
    redirect_to  myorders_path, notice: "La commande est annulée"
  end
end

def set_order
  @order = Order.find(params[:id])
end

end

app/views/orders/_b.html.erb
<%= render 'orders/buttonsachats' %>

<div class="container" id="inbox" style="margin:20px; align-items:center">
<h1>Mes achats en préparation</h1>
<% if @orders.count == 0  %>
  <h3>pas d'achats en préparation, patientez en, <%= link_to "créant une commande!", articles_path %></h3>
  <% end %>
    <div class="row message unread" style="border-bottom: 1px solid #ccc; padding: 0.4em 0; cursor: pointer; font-weight: bold;
  background-color: white;">
      <div class="col-xs-3">Commande</div>
      <div class="col-xs-3">Vendeur</div>
      <div class="col-xs-3">Prix</div>
      <div class="col-xs-3">Actions</div>
    </div>
    <% @orders.each do |order| %>
    <div class="row message read" style="background-color: #eee;">
      <div class="col-xs-3"><%= order.article.name.upcase %> </div>
      <div class="col-xs-3"><%= order.user.first_name %></div>
      <div class="col-xs-3"><%= order.article.price %>€</div>
      <div class="col-xs-3">
        <%= link_to "", destroy_order_path(order), method: :delete, class: "fa fa-ban", style: "color:#6D516B; font-size:50px; left:50px; align-items: right;"%>
      </div>
    </div>
    <% end %>
  </div>

app/views/orders/_buttonsachats.html.erb
<nav>

 <div class="tabs tabs-style-iconbox text-center">
 <ul class="list-inline">
 <li>
<%= link_to "Mes achats en cours", myorders_path(status: :en_cours), class: "" %>
</li>
<li>
<%= link_to "Mes achats en préparation", myorders_path(status: :a_preparer), class: "" %>
</li>
<li>
<%= link_to "Mes achats à récupérer", myorders_path(status: :confirme), class: "" %>
</li>
<li>
<%= link_to "Historique", myorders_path(status: :livre), class: "" %>
</li>
</ul>
</div>

   </nav>

app/views/orders/_buttonsventes.html.erb
<nav>

 <div class="tabs tabs-style-iconbox text-center">
 <ul class="list-inline">
 <li>
<%= link_to "Mes produits", mysales_path(status: :en_cours) %>
</li>
<li>
<%= link_to "Mes commandes à préparer", mysales_path(status: :a_preparer), class: "" %>
</li>
<li>
<%= link_to "Mes commandes en attente pickup", mysales_path(status: :confirme), class: "" %>
</li>
<li>
<%= link_to "Historique", mysales_path(status: :livre), class: "" %>
</li>
</ul>
</div>

   </nav>

app/views/orders/_c.html.erb
<%= render 'orders/buttonsachats' %>

<div class="container" id="inbox" style="margin:20px; align-items:center">
<h1>Mes achats à récupérer</h1>
<% if @orders.count == 0  %>
  <h3>pas d'achats à récupérer, patientez en, <%= link_to "créant une commande!", articles_path %></h3>
  <% end %>
    <div class="row message unread" style="border-bottom: 1px solid #ccc; padding: 0.4em 0; cursor: pointer; font-weight: bold;
  background-color: white;">
      <div class="col-xs-3">Commande</div>
      <div class="col-xs-3">Vendeur</div>
      <div class="col-xs-3">Prix</div>
      <div class="col-xs-3">Actions</div>
    </div>
    <% @orders.each do |order| %>
    <div class="row message read" style="background-color: #eee;">
      <div class="col-xs-3"><%= order.article.name.upcase %> </div>
      <div class="col-xs-3"><%= order.user.first_name %></div>
      <div class="col-xs-3"><%= order.article.price %>€</div>
      <div class="col-xs-3">
        <%= link_to "", change_statut_path(order, status: :livre), class: "fa fa-check-circle", style: "color:#6D516B; font-size:50px; left:50px; align-items: right;"%>
      </div>
    </div>
    <% end %>
  </div>

app/views/orders/_e.html.erb
<%= render 'orders/buttonsventes' %>

<div class="container" id="inbox" style="margin:20px; align-items:center">
<h1>Mes commandes à préparer</h1>
    <div class="row message unread" style="border-bottom: 1px solid #ccc; padding: 0.4em 0; cursor: pointer; font-weight: bold;
  background-color: white;">
      <div class="col-xs-3">Commande</div>
      <div class="col-xs-3">Acheteur</div>
      <div class="col-xs-3">Prix</div>
      <div class="col-xs-3">Actions</div>
    </div>
    <% @orders.each do |order| %>
    <div class="row message read" style="background-color: #eee;">
      <div class="col-xs-3"><%= order.article.name.upcase %> </div>
      <div class="col-xs-3"><%= order.user.first_name %></div>
      <div class="col-xs-3"><%= order.article.price %>€</div>
      <div class="col-xs-3">
        <%= link_to "", change_statut_path(order, status: :confirme), class: "fa fa-check-circle", style: "color:#6D516B; font-size:50px;"  %>
      </div>
    </div>
    <% end %>
  </div>

app/views/orders/_f.html.erb
<%= render 'orders/buttonsventes' %>

<div class="container" id="inbox" style="margin:20px; align-items:center">
<h1>Mes commandes en attente pickup</h1>
    <div class="row message unread" style="border-bottom: 1px solid #ccc; padding: 0.4em 0; cursor: pointer; font-weight: bold;
  background-color: white;">
      <div class="col-xs-3">Commande</div>
      <div class="col-xs-3">Acheteur</div>
      <div class="col-xs-3">Prix</div>
      <div class="col-xs-3">Actions</div>
    </div>
    <% @orders.each do |order| %>
    <div class="row message read" style="background-color: #eee;">
      <div class="col-xs-3"><%= order.article.name.upcase %> </div>
      <div class="col-xs-3"><%= order.user.first_name %></div>
      <div class="col-xs-3"><%= order.article.price %>€</div>
      <div class="col-xs-3">
      </div>
    </div>
    <% end %>
  </div>

app/views/orders/_form.html.erb
<div class="container_form">

  <div class="row">
    <%= simple_form_for @article do |f| %>
    <%= f.error_notification %>

    <div class="col-xs-12">
      <%= f.input :name, placeholder: "Nom", label: false %>
    </div>
    <div class="col-xs-12">
      <%= f.input :description, placeholder: "Description", label: false%>
    </div>
    <div>
      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <div class="form-group">
          <%= f.input :quantity, placeholder: "Qte", label:false  %>
        </div>
      </div>
      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <div class="form-group">
          <%= f.input :unit, placeholder: "Unitée", collection: Article.units, label:false %>
        </div>
      </div>
      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <div class="form-group">
          <%= f.input :price, placeholder: "Prix", label:false %>
        </div>
      </div>
      <div class="text-center">
        <div class="col-xs-12">
          <div class="form-group">
            <%= f.input :photo, as: :attachinary, placeholder: "chemin image", label:false %>
          </div>
        </div>
        <%= f.input :delivery_date, label: "Date de livraison" %>
        <%= f.submit "Valider", class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>

app/views/orders/_formuploadfichier.html.erb
<h2>Chargez vos articles depuis un .CSV</h2>

app/views/orders/_mesproduits.html.erb
<%= render 'orders/buttonsventes' %>
  <div class="row">
<div class="container" id="mesProduits">
  <h1>Mes produits</h1>
    <div class="col-md-2 col-lg-4 col-xs-12">
      <p>Ajoutez un article</p>
      <%= render 'form', article: @article %>
    </div>
    </div>
    <div class="container" id="inbox">
    <div class="col-md-2 col-lg-8 col-xs-12">
        <% if @articles.count == 0  %>
        <h3>pas de produits, faites vous plaiz', créez en un!</h3>
        <% end %>
        <div class="row message unread" style="border-bottom: 1px solid #ccc; padding: 0.4em 0; cursor: pointer; font-weight: bold;
        background-color: white;">
        <div class="col-xs-4">Produits</div>
        <div class="col-xs-1">Prix</div>
        <div class="col-xs-4">Vendeur</div>
      </div>
      <% @articles.each do |article| %>
      <div class="row message read" style="background-color: #eee;">
        <div class="col-xs-4"><%= article.description %> </div>
        <div class="col-xs-1"><%=  article.price  %>€</div>
        <div class="col-xs-4"><%= article.user.first_name + " " + article.user.last_name %> -
          <%= link_to "", article_path(article), method: :post, class: "fa fa-pencil-square-o", style: "color:#6D516B; font-size:40px;" %>
          <%= link_to "", article_path(article), method: :delete, class: "fa fa-trash-o", style: "color:#6D516B; font-size:40px;" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/_mesproduitts.html.erb
<div class="container" id="mesProduits">
    <h1>Mes produits</h1>
  <div class="col-md-4 col-lg-4 col-xs-12">
    <%= render 'form', article: @article %>
  </div>
  <div class="col-md-8 col-lg-8 col-xs-12">
    <% @articles.each do |article| %>
    <div class="col-xs-10">
      <b> <%= article.name %>  </b><i> (<%= article.quantity%>(<%= article.unit %>)</i>
      <br
      <%= article.description %>
      <br>
      prix : <i><b><%= article.price %>€</b></i>
      <br>
      vendeur : <%= article.user.first_name + " " + article.user.last_name %>
      <br>
      ---------------------
    </div>
    <% end %>
  </div>
</div>

app/views/orders/a.html.erb
<%= render 'orders/buttonsachats' %>

<div class="container" id="inbox" style="margin:20px; align-items:center">
<h1>Mes achats en cours</h1>
<% if @orders.count == 0  %>
  <h3>pas d'achats en cours, <%= link_to "créez une commande!", articles_path %></h3>
  <% end %>
    <div class="row message unread" style="border-bottom: 1px solid #ccc; padding: 0.4em 0; cursor: pointer; font-weight: bold;
  background-color: white;">
      <div class="col-xs-3">Commande</div>
      <div class="col-xs-3">Vendeur</div>
      <div class="col-xs-3">Prix</div>
      <div class="col-xs-3">Actions</div>
    </div>
    <% @orders.each do |order| %>
    <div class="row message read" style="background-color: #eee;">
      <div class="col-xs-3"><%= order.article.name.upcase %> </div>
      <div class="col-xs-3"><%= order.user.first_name %></div>
      <div class="col-xs-3"><%= order.article.price %>€</div>
      <div class="col-xs-3">
        <%= link_to "", destroy_order_path(order), method: :delete, class: "fa fa-trash-o", style: "color:#6D516B; font-size:50px; left:50px; align-items: right;"%>
        <%= link_to "", change_statut_path(order, status: :a_preparer), class: "fa fa-check-circle", style: "color:#6D516B; font-size:50px;" %>
      </div>
    </div>
    <% end %>
  </div>

app/views/orders/myorders.html.erb
<%=  render 'buttonsachats'%>

<h2>Balladez vous dans vos commandes</h2>

app/views/orders/mysales.html.erb
<%= link_to "back", articles_path, class: "btn btn-primary" %>

<div class="btn btn-primary en-cours">Mes produits</div>
<div class="btn btn-primary a-recuperer">Mes commandes à préparer</div>
<div class="btn btn-primary historique">Mes commandes en attente pickup</div>
<div class="btn btn-primary historique">Historique</div> <br><br>

<div class="container">
  <div class="row">
    <h1>Mes produits</h1>
    <div class="col-md-4 col-lg-4 col-xs-12">
      <%= render 'form', article: @article %>
    </div>
  </div>
</div>
<div class="col-md-8 col-lg-8 col-xs-12">
  <% @articles.each do |article| %>
  <div class="col-xs-10">
    <b> <%= article.name %>  </b><i> (<%= article.quantity%>(<%= article.unit %>)</i>
    <br
    <%= article.description %>
    <br>
    prix : <i><b><%= article.price %>€</b></i>
    <br>
    vendeur : <%= article.user.first_name + " " + article.user.last_name %>
    <br>
    ---------------------
  </div>
  <% end %>
</div>
</div>

<div class="container">
  <h1>Mes commandes à préparer</h1>
  <div class="col-md-8 col-lg-8 col-xs-12">
    <% @orders_a_preparer.each do |order| %>
    <div class="col-xs-10">
      <b> <%= order.article.name %>  </b><i> (<%= order.status %>)</i>
      <br>
      <%= order.article.quantity %>
      <%= order.article.unit %>
      <br>
      prix : <i><b><%= order.article.price %>€</b></i>
      <br>
      vendeur : <%= order.article.user.first_name + " " + order.article.user.last_name %>
      <br>
      ---------------------
    </div>
    <div class="col-xs-2">
      <%= link_to "preparation ok", change_statut_path(order, status: :confirme), class: "btn btn-primary" %>
    </div>
    <% end %>
  </div>
</div>

<div class="container">
  <h1>Mes commandes en attente pickup</h1>
  <div class="col-md-8 col-lg-8 col-xs-12">
    <% @orders_livre.each do |order| %>
    <div class="col-xs-10">
      <b> <%= order.article.name %>  </b><i> (<%= order.status %>)</i>
      <br>
      <%= order.article.quantity %>
      <%= order.article.unit %>
      <br>
      prix : <i><b><%= order.article.price %>€</b></i>
      <br>
      vendeur : <%= order.article.user.first_name + " " + order.article.user.last_name %>
      <br>
      ---------------------
    </div>
    <div class="col-xs-2">
      <!-- btn à mettre -->
    </div>
    <% end %>
  </div>

</div>

<div class="container">
  <h1>Historique</h1>
  <div class="col-md-8 col-lg-8 col-xs-12">
    <% @orders_termine.each do |order| %>
    <div class="col-xs-10">
      <b> <%= order.article.name %>  </b><i> (<%= order.status %>)</i>
      <br>
      <%= order.article.quantity %>
      <%= order.article.unit %>
      <br>
      prix : <i><b><%= order.article.price %>€</b></i>
      <br>
      vendeur : <%= order.article.user.first_name + " " + order.article.user.last_name %>
      <br>
      ---------------------
    </div>
    <div class="col-xs-2">
      <!-- btn à mettre -->
    </div>
    <% end %>
  </div>

</div>

<%= render 'orders/buttonsventes' %>

app/views/orders/test.html.erb
<!-- bouton 1 à cliquer -->
<div class="btn btn-primary">Commandes en cours</div>

<br><br>

<div class="test">
<h1>it's a test</h1>
</div>

<br>

<div class="test-2">
<p>lalala</p>
</div>

<script>
  $('.btn').on('click', function(){ alert("CLICK OK"); });
</script>